version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@db:5432/postgres?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  restore:
    image: postgres:17-alpine
    depends_on:
      - db
    volumes:
      - ./public/restore_base.sql:/restore_base.sql
    environment:
      - PGPASSWORD=admin
    command: >
      sh -c "apk add --no-cache postgresql-client &&
            sleep 10 &&
            ls -l /restore_base.sql &&
            pg_restore -h db -U postgres -d postgres -1 /restore_base.sql"

volumes:
  postgres_data:
